development:
  adapter: mysql
  database: innovationsq_development
  user: root
  pass:
  timeout: 5000

test:
  adapter: mysql
  database: innovationsq_test
  user: root
  pass:
  timeout: 5000

production:
  adapter: mysql
  database: heroku_override
  pool: 5
  timeout: 5000
